FORMAT: 1A
HOST: http://avatar-api.thekiwi.online/

# Avatar API

The Avatar API is implemented as JSON over HTTP. 
Our API is designed to have predictable, resource oriented URLs and use HTTP 
response codes to indicate API errors. 
Our API resources try to mirror schema.org schemas naming conventions where possible. 
To make the Avatar API as explorable as possible, accounts have testmode API keys as 
well as live-mode API keys. These keys can be active at the same time.

##General Notes
###SSL Only
We require that all requests are done over SSL. Requests made over plain HTTP will fail.
###UTF-8 Encoding
Every string passed to and from the Avatar API needs to be UTF-8 encoded
###Date Format
All dates in the Avatar API are strings in the following format:

`"Sat, 21 Aug 2010 22:31:20 +0000"`

In code format, which can be used in all programming languages that support strftime or strptime:

`"%a, %d %b %Y %H:%M:%S %z"`

###Authentication
You need to authenticate to the Avatar API by providing one of your API keys in the request. You can manage your keys from your account.
You can have multiple keys with different access rights active at the same time.

Your API keys carry many privileges, so be sure to keep them secret!

##Standard Server Responses##

+ 200 `OK` - the request was successful.
+ 201 `Created` - the request was successful and a resouce was created.
+ 400 `Bad Request` - the request could not be understood or was missing required parameters.
+ 401 `Unauthorized` - authentication failed or user doesn't have permission for requested operation.
+ 402 `Request Failed` - the request was valid but failed.
+ 403 `Forbidden` - access denied.
+ 404 `Not Found` - resource was not found.
+ 405 `Method Not Allowed` - requested method is not supported for resource.

##ERRORS
Avatar API uses standard HTTP response codes to indicate success or failure of an API request. In general, codes in the 2xx range indicate success,
codes in the 4xx range indicate an error that resulted from the provided information (e.g. a required parameter was missing), and codes in the
5xx range indicate an error with PayMe's servers.

Not all errors map cleanly onto HTTP response codes, however. When a request is valid but does not complete successfully (e.g. a payment is declined),
we return a 402 error code.

All errors will raise an exception with a type, a message describing this particular problem to the developer, and an optional user-friendly message that can
be used for display purposes (e.g. Your payment was declined).

####Error Attributes

- **type:** The type of error returned, will be one of:
    - *invalid_request_error* : Invalid request errors arise when your request has invalid parameters or you are not allowed to make such a request (API Key restrictions).  
    - *api_error*             : API errors cover any other type of problem (e.g. a temporary problem with AVATAR's servers) and should only show up very infrequently.

- **message:** Developer facing message describing the error.
- **user_message:** *(optional)* A user-friendly message that can be used to inform end user of the error.
- **parameters:** *(optional)* The parameter(s) the error relates to if the error is parameter related.

####Example Error Response (Body)

```JSON
{
   "error":[
      {
         type: "invalid_request_error",
         message: "",
         user_message: "",
         parameters: ""
      }
   ]
}
```
        
## AVATARS Collection [/avatars]

### Register a New AVATAR [POST]

You may create your own avatar using this action. It simply takes a JSON
object containing an address which should contain an ethereum address.

+ Request (application/json)

    + Body
    
            {
                "address": "0xE9ACe1e7AD2C506D2FB60fAD481887Fc39819714"
            }

+ Response 201 (application/json)

    + Headers

            Location: /avatars/0xE9ACe1e7AD2C506D2FB60fAD481887Fc39819714

    + Body

            {
                address: "0xE9ACe1e7AD2C506D2FB60fAD481887Fc39819714",
                created_at: "2015-08-05T08:40:51.620Z",
            }
            
### Get AVATAR [GET]

Get all data held against an avatar. It simply takes a JSON object containing an address
and returns a JSON object which references datasets.

+ Request (application/json)

    + Body
    
            {
                address: "0xE9ACe1e7AD2C506D2FB60fAD481887Fc39819714"
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                address: "0xE9ACe1e7AD2C506D2FB60fAD481887Fc39819714",
                updated_at: "2015-08-05T08:40:51.620Z",
                datasets: {
                    general: "g56261526",
                    hobbies: "hj1h2jh1j2j"
                }
            }
            
### DELETE AVATAR [DELETE]

Delete an Avatar. This action needs to be initiated by the Avatar owner. 
The signedtx is a signed message created by the user using a passcode that only they know

+ Request (application/json)

    + Body
    
            {
                address: "0xE9ACe1e7AD2C506D2FB60fAD481887Fc39819714"
                signedtx: "0x9955af11969a2d2a7f860cb00e6a00cfa7c581f5df2dbe8ea16700b33f4b4b9b69f945012f7ea7d3febf11eb1b78e1adc2d1c14c2cf48b25000938cc1860c83e01"
            }

+ Response 204


## Datasets Collection [/datasets]
    
### Get information about all datasets [GET]

This request will return information about all public datasets. 

+ Response 200

    + Body
    
            {
                general: {
                    created_on: "2015-08-05T08:40:51.620Z",
                    last_updated: "2015-08-05T08:40:51.620Z"
                    datapoints: 15
                }
            }
            
## Dataset [/dataset/{id}]

### Get information about a dataset [GET]

+ Request (application/json)

    + Body
    
            {
                id: "general"
            }
            
+ Response 200 (application/json)

    + Body
        
            {
                id: "general"
                datapoints: {
                    gender: {
                        type: select,
                        question: "What gender are you?",
                        options: "male,female",
                    },
                    birthdate: {
                        type: date,
                        question: "What is your birthdate?"
                    },
                    age: {
                        type: number,
                        calculated: true,
                        notes: "This datapoint is calculated from the Avatar birthdate."
                    }
                }
            }